/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisplayTable: typeof import('./src/components/shared/DisplayTable.vue')['default']
    FormError: typeof import('./src/components/shared/FormError.vue')['default']
    InputCheckbox: typeof import('./src/components/shared/InputCheckbox.vue')['default']
    InputHelpIcon: typeof import('./src/components/shared/InputHelpIcon.vue')['default']
    InputSelect: typeof import('./src/components/shared/InputSelect.vue')['default']
    InputText: typeof import('./src/components/shared/InputText.vue')['default']
    InputTextarea: typeof import('./src/components/shared/InputTextarea.vue')['default']
    LoadingScreen: typeof import('./src/components/shared/LoadingScreen.vue')['default']
    LogoSvg: typeof import('./src/components/shared/LogoSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteDisclaimer: typeof import('./src/components/site/SiteDisclaimer.vue')['default']
    SiteErrorPage: typeof import('./src/components/site/SiteErrorPage.vue')['default']
    SiteFooter: typeof import('./src/components/site/SiteFooter.vue')['default']
    SiteFooterNav: typeof import('./src/components/site/SiteFooterNav.vue')['default']
    SiteHeader: typeof import('./src/components/site/SiteHeader.vue')['default']
    SiteLogo: typeof import('./src/components/site/SiteLogo.vue')['default']
    SiteMessage: typeof import('./src/components/site/SiteMessage.vue')['default']
    SiteMessageAlert: typeof import('./src/components/site/SiteMessageAlert.vue')['default']
    SiteNavigation: typeof import('./src/components/site/SiteNavigation.vue')['default']
    SitePageTitle: typeof import('./src/components/site/SitePageTitle.vue')['default']
    SubmitButton: typeof import('./src/components/shared/SubmitButton.vue')['default']
    TablePagination: typeof import('./src/components/shared/TablePagination.vue')['default']
    ThemeToggleButton: typeof import('./src/components/shared/ThemeToggleButton.vue')['default']
    ToTheTop: typeof import('./src/components/shared/ToTheTop.vue')['default']
  }
}
